#pragma once

#include <QtWidgets/QMainWindow>
#include <QObject>
#include <QLayoutItem>
#include <QGridLayout>
#include <QColorDialog>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QWidget>
#include <QFormLayout>
#include <QSpinBox>
#include <QCheckBox>
#include <QMenuBar>
#include <QDockWidget>
#include <QVBoxLayout>
#include <QPushButton>
#include <QLineEdit>
#include <QPalette>
#include <QLabel>
#include <QFrame>
#include <QComboBox>
#include <QHBoxLayout>
#include <QWheelEvent>
#include <QGraphicsItem>
#include <QScrollBar>
#include <QRectF>
#include <QTextEdit>
#include <QStringBuilder>

#include <QTcpSocket>
#include <QHostAddress>
